### ISSUE TITLE
Congestion issues with pop and push

### ISSUE THREAD

**Issue by gronron** [rigtorp/MPMCQueue#18]
Hello,

I was benchmarking your MPMCQueue with [https://gist.github.com/TurpentineDistillery/cba204646e631a3eeda5b06cac595fde](https://gist.github.com/TurpentineDistillery/cba204646e631a3eeda5b06cac595fde) on my Ryzen R9 3900x (windows 10).
And I noticed that the MPMCQueue has struggles with the last benchmark (128 producers and 128 consumer). I test with 24/24 and it is still slow.

So with this benchmak I tried to use:
template<typename T>
void push(rigtorp::MPMCQueue<T>& q, T value)
{
    while(!q.try_push(value)) {
        mt::min_sleep();
    }
}

template<typename T>
T pop(rigtorp::MPMCQueue<T>& q)
{
    T item{};
    while(!q.try_pop(item)) {
        mt::min_sleep();
    }
    return item;
}

And the performance on the 24/24 and 96/96 was nice.
I don't understand why the initial pop and push has so bad performance when there are far more thread than my CPU can handle.

Thanks you.

**Comment by rigtorp** [comment]
Sorry for the late reply.

Your CPU has 24 hardware threads. When you go beyond 24 threads using this
queue you will run into issues when doing blocking push or pop since
threads that are blocked will not give up the CPU to the scheduler. This is
the same issue as with spinlocks. Using futex directly or the new C++20
https://en.cppreference.com/w/cpp/atomic/atomic_wait API the queue can be
modified to efficiently wait during blocking operations. I haven't
implemented this since it's not the behavior I desire in my use-cases.
